// Auto-generated file - do not edit manually
// Generated by scripts/generate-sprite.ts

export type SpriteIconName =
  | 'audio-lines'
  | 'brain-cog'
  | 'database'
  | 'flag'
  | 'globe'
  | 'image'
  | 'alarm-clock'
  | 'braces'
  | 'cake-slice'
  | 'calendar'
  | 'chevrons-down'
  | 'fingerprint'
  | 'letter-text'
  | 'link'
  | 'message-square'
  | 'messages-square'
  | 'octagon-x'
  | 'skull'
  | 'siren'
  | 'save'
  | 'scan-eye'
  | 'scroll-text'
  | 'shield-alert'
  | 'square-stop'
  | 'wrench'
  | 'file-chart-column-increasing'
  | 'file-spreadsheet'
  | 'file-text'
  | 'file-up'
  | 'image-down'
  | 'image-up'
  | 'bug'

/**
 * Get the sprite URL for an icon (for use in <use> elements)
 */
export function getSpriteUrl(iconName: SpriteIconName): string {
  return `/sprites/lucide-sprite.16cb546f.svg#lucide-${iconName}`
}
